config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
   root :to => "homes#top"
   get "about" => "homes#about"
   resource :customers, only: [:show, :edit, :update]
   get "customers/my_page" => "customers#show"
   get "customers/unsubscribe" => "customers#unsubscribe"
   patch "customers/withdraw" => "customers#withdraw"

   resources :addresses, except: [:show, :new]
   
   resources :items, only: [:index, :show]
   
   resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
   end
    
   resources :orders, only: [:index, :show, :new, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
   end



  end


  devise_for :admins, path: "/admin", controllers: {
    sessions: 'admin/sessions'

  }

 scope module: :public do
    devise_for :customers, controllers: {
      sessions: 'public/sessions',
      passwords: 'public/passwords',
      registrations: 'public/registrations'
    }
 end





  namespace :admin do
   root :to => 'homes#top'
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [ :show, :update] do
      patch "admin/order_details/:id" => "order_details#update", as: "order_detail"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
            
  def active_for_authentication?
    super && (is_active?)
  end  
            
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
    render "edit"
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id), notice: "会員情報を変更しました"
    else
      render "edit"
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_active)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="edit-title">
    <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
  </div>
</div>

<div class="row">
   <div class="col-2"></div>
   <div>
     <%= form_with( model: @customer, url: admin_customer_path, local: true) do |f| %>
       <div class="row">
         <table class="table table-bordered">
           <tbody>
             <tr>
               <th>会員ID</th>
               <td><%= @customer.id %></td>
             </tr>
             <tr>
               <th>氏名</th>
               <td><%= f.text_field :last_name, id: "adminCustomerLastName" %> <%= f.text_field :first_name, id: "adminCustomerFirstName" %></td>
             </tr>
             <tr>
               <th>フリガナ</th>
               <td><%= f.text_field :last_name_kana, id: "adminCustomerKanaLastName" %> <%= f.text_field :first_name_kana, id: "adminCustomerKanaFirstName" %></td>
             </tr>
             <tr>
               <th>住所</th>
               <td><%= f.text_field :address, id: "adminCustomerAddress" %></td>
             </tr>
             <tr>
               <th>電話番号</th>
               <td><%= f.text_field :phone_number, id: "adminCustomerPhoneNumber" %></td>
             </tr>
             <tr>
               <th>メールアドレス</th>
               <td><%= f.text_field :email, id: "adminCustomerEmail" %></td>
             </tr>
             <tr>
               <th>会員ステータス</th>
               <td>
                 <%= f.label :is_active, '有効', value: true %>
                 <%= f.radio_button :is_active, true %>
                 <%= f.label :is_active, '無効', value: false %>
                 <%= f.radio_button :is_active, false %>
               </td>
             </tr>
           </tbody>
         </table>
       </div>
      <%= f.submit '変更を保存', class: "btn btn-success" %>
      <% end %>
    </div>
    <div class="col-2"></div>
</div>

app/views/admin/customers/index.html.erb
<div class="col-2">
  <div class="col mx-auto">
    <h4>会員一覧</h4>
  </div>
  <div class="col-8"></div>
</div>

<div class="row table-row">
  <div class="col-8 mx-auto">
    <table class="table">
      <thead class="thead-light">
       <tr>
         <th>会員ID</th>
         <th>氏名</th>
         <th>メールアドレス</th>
         <th>ステータス</th>
       </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to "#{customer.last_name} #{customer.first_name}", admin_customer_path(customer.id), class: "text-dark border-bottom border-dark" %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_active == true %>
                <p class="text-success">有効</p>
              <% else %>
                <p class="text-secondary">退会</p>
              <% end %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
    <div class="row">
      <div class="admin-heading col-12">
        <h2 class="mb-4 pt-3 pb-3 text-center"><%= "#{@customer.last_name}""#{@customer.first_name}" %>さんの会員詳細</h2>
      </div>
      <div class="col-8 mx-auto mb-5 admin-customer-show">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th>会員ID</th>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <th>氏名</th>
              <td><%= @customer.last_name %> <%= @customer.first_name %></td>
            </tr>
            <tr>
              <th>フリガナ</th>
              <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
            </tr>
            <tr>
              <th>郵便番号</th>
              <td><%= @customer.postal_code %></td>
            </tr>
            <tr>
              <th>住所</th>
              <td><%= @customer.address %></td>
            </tr>
            <tr>
              <th>電話番号</th>
              <td><%= @customer.phone_number %></td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td><%= @customer.email %></td>
            </tr>
            <tr>
              <th>会員ステータス</th>
              <td>
                <% if @customer.is_active == true %>
                  <p class="text-success">有効</p>
                <% else %>
                  <p class="text-secondary">退会</p>
                <% end %>
              </td>
            </tr>
            <tr>
              <th></th>
              <td>
                <%= link_to "編集する", edit_admin_customer_path, class: "btn mr-5 btn-success" %>
                <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>