config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
   root :to => "homes#top"
   get "about" => "homes#about"
   resource :customers, only: [:show, :edit, :update]
   get "customers/my_page" => "customers#show"
   get "customers/unsubscribe" => "customers#unsubscribe"
   patch "customers/withdraw" => "customers#withdraw"

   resources :addresses, except: [:show, :new]
   
   resources :items, only: [:index, :show]
   
   resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
   end
    
   resources :orders, only: [:index, :show, :new, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
   end



  end


  devise_for :admins, path: "/admin", controllers: {
    sessions: 'admin/sessions'

  }

 scope module: :public do
    devise_for :customers, controllers: {
      sessions: 'public/sessions',
      passwords: 'public/passwords',
      registrations: 'public/registrations'
    }
 end





  namespace :admin do
   root :to => 'homes#top'
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [ :show, :update] do
      patch "admin/order_details/:id" => "order_details#update", as: "order_detail"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy


  validates :customer_id, :address, :name, :shipping_cost, :total_payment, :payment_method, presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :shipping_cost, :total_payment, numericality: { only_integer: true }

  enum payment_method: {"クレジットカード": 0, "銀行振込": 1}
  enum status: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!


  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.status == "入金確認"
        @order.order_details.each do |order_detail|
          order_detail.update(making_status: 1)
       end
      end
    end

  flash[:notice] = "注文ステータスを変更しました。"
   redirect_to admin_order_path(@order)
  end
  private

  def order_params
    params.require(:order).permit(:status)
  end




end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="admin-heading col-md-12">
      <h3 class="mb-4 col-3 pt-2 pb-2">注文履歴詳細</h3>
    </div>
    <table class="table table-sm mb-3 admin-order-show-table">
      <tbody>
        <tr>
          <th>購入者</th>
          <td><%= link_to "#{@order.customer.last_name} #{@order.customer.first_name}", admin_customer_path(@order.customer.id), class: "text-dark border-bottom border-dark" %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order), local: true do |f| %>
              <%= f.select :status, [["入金待ち", "入金待ち"], ["入金確認", "入金確認"], ["製作中", "製作中"], ["発送準備中", "発送準備中"], ["発送済み", "発送済み"]], class: "form-control" %>
              <%= f.submit "更新", class: "btn ml-3 btn btn-outline-success btn-sm" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="row mb-5">
    <div class="col-7">
      <table class="table mt-3 table-borderless table-hover rounded-top rounded-bottom table_border_radius admin-order-table">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @sum = 0 %>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td>
              <% @order_details = order_detail.item.with_tax_price * order_detail.amount %>
              <%= @order_details.to_s(:delimited) %>
            </td>
            <td>
              <%= form_with model: order_detail, url: admin_order_order_detail_path(@order, order_detail), local: true do |f| %>
                <%= f.select :making_status, [["着手不可", "着手不可"], ["製作待ち", "製作待ち"], ["製作中", "製作中"], ["製作完了", "製作完了"]], class: "form-control" %>
                <%= f.submit "更新", class: "btn ml-3 btn btn-outline-success btn-sm" %>
              <% end %>
            </td>
            <% @sum += @order_details %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= @sum.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td>800円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><% @order_details = @sum + 800 %>
                <%= @order_details.to_s(:delimited) %>円
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>