config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
   root :to => "homes#top"
   get "about" => "homes#about"
   resource :customers, only: [:show, :edit, :update]
   get "customers/my_page" => "customers#show"
   get "customers/unsubscribe" => "customers#unsubscribe"
   patch "customers/withdraw" => "customers#withdraw"

   resources :addresses, except: [:show, :new]
   
   resources :items, only: [:index, :show]
   
   resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete 'destroy_all'
      end
   end
    
   resources :orders, only: [:index, :show, :new, :create] do
      collection do
        post 'confirm'
        get 'complete'
      end
   end



  end


  devise_for :admins, path: "/admin", controllers: {
    sessions: 'admin/sessions'

  }

 scope module: :public do
    devise_for :customers, controllers: {
      sessions: 'public/sessions',
      passwords: 'public/passwords',
      registrations: 'public/registrations'
    }
 end





  namespace :admin do
   root :to => 'homes#top'
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [ :show, :update] do
      patch "admin/order_details/:id" => "order_details#update", as: "order_detail"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ } #郵便番号ハイフンなし7桁
  validates :address, presence: true
  validates :name, presence: true
  
  def view_address
    "〒" + self.postal_code + "　" + self.address + "　" + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def tax_in_price
    (price * 1.1).floor
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :customer
   belongs_to :item


   validates :amount, numericality:{ only_integer: true }, presence: true
   
   def with_tax_price
    (price * 1.1).floor
   end

   def subtotal
    item.with_tax_price * amount
   end



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
            
  def active_for_authentication?
    super && (is_active?)
  end  
            
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
    
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    
    attachment :image
    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_many :orders, through: :order_details
    belongs_to :genre, class_name: 'Genre', foreign_key: 'genre_id'

    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    validates :genre, presence: true
 
     def with_tax_price
      (price * 1.1).floor
     end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy


  validates :customer_id, :address, :name, :shipping_cost, :total_payment, :payment_method, presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :shipping_cost, :total_payment, numericality: { only_integer: true }

  enum payment_method: {"クレジットカード": 0, "銀行振込": 1}
  enum status: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  validates :item_id, :order_id, :amount, :price, presence: true
  validates :price, :amount, numericality: { only_integer: true }
  enum making_status: {"着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!


  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre =Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end

  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render "edit"
    end

  end

  private
   def genre_params
    params.require(:genre).permit(:name)
   end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    if params[:customers_id]
      #遷移してきたIDをwhereで取得
      @orders = order.where(customer_id: params[:customer_id]).page(params[:page]).per(10)
    else
      #オーダーデータ全て
      @orders = Order.all.page(params[:page]).per(10).order(created_at: :desc)
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!


   def index
     @items = Item.all.page(params[:page]).per(10)
   end

   def show
     @item = Item.find(params[:id])
   end

   def edit
     @item = Item.find(params[:id])
   end

   def update
     @item = Item.find(params[:id])
     if @item.update(item_params)
       flash[:notice] = "商品詳細変更が完了しました。"
       redirect_to admin_items_path(@item)
     else
       flash[:alert] = "商品詳細の変更内容に不備があります。"
       render :edit
     end
   end

   def new
     @item = Item.new
     @genres = Genre.all
   end

   def create
     @item = Item.new(item_params)
     if @item.save
       flash[:notice] = "商品の新規登録が完了しました。"
       @items = Item.all
       redirect_to admin_item_path(@item.id)
     else
       flash[:alert] = "商品の新規登録内容に不備があります。"
       render :new
     end
   end

   private
   def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
   
   def after_sign_in_path_for(resource)
     case resource
     when Admin
       flash[:notice] = "ログインに成功しました"
       admin_root_path
     when Customer
       flash[:notice] = "ログインに成功しました"
       root_path
     end
   end
   
   def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
     root_path
    elsif resource_or_scope == :admin
     new_admin_session_path
    else
     root_path
    end
      
   end 
          
  
   protected
       #新規登録保存機能
     def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :first_name, :last_name, :first_name_kana, :last_name_kana, :email, :postal_code, :encrypted_password, :phone_number, :address])
        #sign_upの際にnaameのデータ操作を許可。追加したカラム
       devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
     end  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_header.html.erb
<% unless admin_signed_in? %>
  <% # adminサインイン前は会員側のヘッダーを表示 %>
  <%= render "public/shared/header" %>
<% else %>
  <% # adminサインイン済み %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
      <%= link_to admin_root_path, class: "navbar-brand" do %>
        <%= image_tag "header_927268.png", { height: 30 } %>
      <% end %>
      <span class="badge badge-danger p-2 mr-auto">管理者ページ</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: model.errors.count,
                 resource: model.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <div class="col-5 alert alert-success" role="alert"><%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% else %>
    <div class="col-5 alert alert-danger" role="alert"><%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center">Nagano Cake © 2021 All rights reserved by Infratop.Inc.</p>
  <div class="d-flex justify-content-center">
    <a href="#" class="mx-1 text-dark"><i class="fab fa-twitter fa-2x"></i></a>
    <a href="#" class="mx-5 text-dark"><i class="fab fa-instagram fa-2x"></i></a>
    <a href="#" class="mx-1 text-dark"><i class="far fa-envelope fa-2x"></i></a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to image_tag("logo.png", size: "80x50"), root_path, class: "image mt-2" %>
      <%= link_to "NaganoCAKE", root_path, class:"header-title navbar-brand"%>


      <button class="navbar-toggler mx-5" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
         <% if customer_signed_in? %>
          <li class="nav-item active">
           <span class="nav-link text-dark">ようこそ<%= current_customer.last_name %> <%= current_customer.first_name %>さん</span>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-secondary mx-3 my-1"%>
          </li>
          <li class="nav-item ">
            <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to "カート", cart_items_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary mx-3 my-1'%>
          </li>
         <% elsif admin_signed_in? %>
           <li class="nav-item">
             <%= link_to "商品一覧", admin_items_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "注文履歴一覧", admin_root_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "ログアウト",destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
         <% else %>
         <li class="nav-item">
             <%= link_to "about", about_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
           </li>
           <li class="nav-item">
             <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
           <li class="nav-item">
             <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
           </li>
          <% end %>
        </ul>
      </div>

 </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name ="viewport" content="width=device-width, initial-scale=1, maximim-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <div id="flash">
        <%= render "layouts/flash" %>
      </div>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>